[project]
name = "stackswap.clarinet"
requirements = []


[contracts.trait-sip-010]
path = "contracts/trait-sip-010.clar"
depends_on = ["trait-sip-010"]

[contracts.restricted-token-trait]
path = "contracts/trait-restricted-token.clar"
depends_on = ["trait-sip-010"]

[contracts.trait-liquidity-token]
path = "contracts/trait-liquidity-token.clar"
depends_on = ["trait-sip-010"]



[contracts.initializable-token-trait]
path = "contracts/trait-initializable-token.clar"
depends_on = ["trait-sip-010"]



[contracts.stackswap-dao]
path = "contracts/stackswap-dao.clar"
depends_on = ["stackswap-dao-token-trait"]




[contracts.stackswap-swap-v1]
path = "contracts/stackswap-swap-v1.clar"
depends_on = ["trait-sip-010", "liquidity-token-trait", "stackswap-swap-fee-v1"]




[contracts.wstx-token]
path = "contracts/token-wstx.clar"
depends_on = ["trait-sip-010"]



[contracts.tokensoft-token-v2]
path = "contracts/token-tokensoft-v2.clar"
depends_on = ["trait-sip-010", "restricted-token-trait", "initializable-token-trait", "stackswap-one-step-mint-fee-v1"]

[contracts.stsw-token]
path = "contracts/token-stsw.clar"
depends_on = ["trait-sip-010", "restricted-token-trait"]

[contracts.stackswap-governance-v1]
path = "contracts/stackswap-governance-v1.clar"
depends_on = ["stsw-token"]




[contracts.liquidity-tokensoft-token]
path = "contracts/liquidity-tokensoft-v1.clar"
depends_on = ["liquidity-token-trait", "stackswap-dao"]


[contracts.stackswap-one-step-mint-v1]
path = "contracts/stackswap-one-step-mint-v1.clar"
depends_on = ["trait-sip-010", "liquidity-token-trait", "stackswap-swap-v1", "wstx-token", "liquidity-tokensoft-token", "tokensoft-token-v2", "poxlsoft-token-v1"]

[contracts.stackswap-one-step-mint-fee-v1]
path = "contracts/stackswap-one-step-mint-fee-v1.clar"
depends_on = ["trait-sip-010"]








[contracts.stackswap-farming-v1]
path = "contracts/stackswap-farming-v1.clar"
depends_on = ["trait-sip-010"]

[contracts.stackswap-router-v1]
path = "contracts/stackswap-router-v1.clar"
depends_on = ["trait-sip-010"]

[contracts.stackswap-security-list]
path = "contracts/stackswap-security-list.clar"
depends_on = ["trait-sip-010"]

[contracts.stackswap-staking]
path = "contracts/stackswap-staking.clar"
depends_on = ["trait-sip-010"]

[contracts.token-poxlsoft-v2]
path = "contracts/token-poxlsoft-v2.clar"
depends_on = ["trait-sip-010"]

[contracts.token-vstsw]
path = "contracts/token-vstsw.clar"
depends_on = ["trait-sip-010"]

[contracts.trait-stackswap-staking]
path = "contracts/trait-stackswap-staking.clar"
depends_on = ["trait-sip-010"]

[contracts.trait-stackswap-swap]
path = "contracts/trait-stackswap-swap.clar"
depends_on = ["trait-sip-010"]






